package com.mssoftech.springreact.domain;
// Generated 2015/8/3 下午 02:20:55 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Login generated by hbm2java
 */
@Entity
@Access(AccessType.PROPERTY)
@Table(name = "login", uniqueConstraints = @UniqueConstraint(columnNames = { "login_id",
		"del_flag" }) )
public class Login implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1438580893193477895L;
	private Integer id;
	private String loginId;
	private String name;
	private String password;
	private int versionNo;
	private int delFlag;
	private Date registerDatetime;
	private String registerUser;
	private String registerProcess;
	private Date updateDatetime;
	private String updateUser;
	private String updateProcess;
	private String role;
	private Set<Session> sessions = new HashSet<Session>(0);

	public Login() {
	}

	public Login(String loginId, String name, String password, int versionNo, int delFlag, Date registerDatetime,
			String registerUser, String registerProcess, Date updateDatetime, String updateUser, String updateProcess) {
		this.loginId = loginId;
		this.name = name;
		this.password = password;
		this.versionNo = versionNo;
		this.delFlag = delFlag;
		this.registerDatetime = registerDatetime;
		this.registerUser = registerUser;
		this.registerProcess = registerProcess;
		this.updateDatetime = updateDatetime;
		this.updateUser = updateUser;
		this.updateProcess = updateProcess;
	}

	public Login(String loginId, String name, String password, int versionNo, int delFlag, Date registerDatetime,
			String registerUser, String registerProcess, Date updateDatetime, String updateUser, String updateProcess,
			String role, Set<Session> sessions) {
		this.loginId = loginId;
		this.name = name;
		this.password = password;
		this.versionNo = versionNo;
		this.delFlag = delFlag;
		this.registerDatetime = registerDatetime;
		this.registerUser = registerUser;
		this.registerProcess = registerProcess;
		this.updateDatetime = updateDatetime;
		this.updateUser = updateUser;
		this.updateProcess = updateProcess;
		this.role = role;
		this.sessions = sessions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "login_id", nullable = false, length = 40)
	public String getLoginId() {
		return this.loginId;
	}

	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}

	@Column(name = "name", nullable = false, length = 40)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "password", nullable = false, length = 40)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "version_no", nullable = false)
	public int getVersionNo() {
		return this.versionNo;
	}

	public void setVersionNo(int versionNo) {
		this.versionNo = versionNo;
	}

	@Column(name = "del_flag", nullable = false)
	public int getDelFlag() {
		return this.delFlag;
	}

	public void setDelFlag(int delFlag) {
		this.delFlag = delFlag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "register_datetime", nullable = false, length = 19)
	public Date getRegisterDatetime() {
		return this.registerDatetime;
	}

	public void setRegisterDatetime(Date registerDatetime) {
		this.registerDatetime = registerDatetime;
	}

	@Column(name = "register_user", nullable = false, length = 30)
	public String getRegisterUser() {
		return this.registerUser;
	}

	public void setRegisterUser(String registerUser) {
		this.registerUser = registerUser;
	}

	@Column(name = "register_process", nullable = false, length = 30)
	public String getRegisterProcess() {
		return this.registerProcess;
	}

	public void setRegisterProcess(String registerProcess) {
		this.registerProcess = registerProcess;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_datetime", nullable = false, length = 19)
	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

	@Column(name = "update_user", nullable = false, length = 30)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@Column(name = "update_process", nullable = false, length = 30)
	public String getUpdateProcess() {
		return this.updateProcess;
	}

	public void setUpdateProcess(String updateProcess) {
		this.updateProcess = updateProcess;
	}

	@Column(name = "role", length = 20)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@OneToMany(mappedBy = "login")
	public Set<Session> getSessions() {
		return this.sessions;
	}

	public void setSessions(Set<Session> sessions) {
		this.sessions = sessions;
	}

}
