package com.mssoftech.springreact.domain;
// Generated 2015/8/3 下午 02:20:55 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Type;

/**
 * SysTable generated by hbm2java
 */
@Entity
@Table(name = "sys_table", uniqueConstraints = @UniqueConstraint(columnNames = {"table_name", "key_1", "key_2", "del_flag" }) )
public class SysTable implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8532034548036491479L;
	private Integer id;
	private String tableName;
	private String key1;
	private String key2;
	private String s1Data;
	private String s2Data;
	private String s3Data;
	private BigDecimal n1Data;
	private BigDecimal n2Data;
	private BigDecimal n3Data;
	private int versionNo;
	private int delFlag;
	private Date registerDatetime;
	private String registerUser;
	private String registerProcess;
	private Date updateDatetime;
	private String updateUser;
	private String updateProcess;

	public SysTable() {
	}

	public SysTable(String tableName, String key1, String key2, int versionNo, int delFlag, Date registerDatetime,
			String registerUser, String registerProcess, Date updateDatetime, String updateUser, String updateProcess) {
		this.tableName = tableName;
		this.key1 = key1;
		this.key2 = key2;
		this.versionNo = versionNo;
		this.delFlag = delFlag;
		this.registerDatetime = registerDatetime;
		this.registerUser = registerUser;
		this.registerProcess = registerProcess;
		this.updateDatetime = updateDatetime;
		this.updateUser = updateUser;
		this.updateProcess = updateProcess;
	}

	public SysTable(String tableName, String key1, String key2, String s1Data, String s2Data, String s3Data,
			BigDecimal n1Data, BigDecimal n2Data, BigDecimal n3Data, int versionNo, int delFlag, Date registerDatetime,
			String registerUser, String registerProcess, Date updateDatetime, String updateUser, String updateProcess) {
		this.tableName = tableName;
		this.key1 = key1;
		this.key2 = key2;
		this.s1Data = s1Data;
		this.s2Data = s2Data;
		this.s3Data = s3Data;
		this.n1Data = n1Data;
		this.n2Data = n2Data;
		this.n3Data = n3Data;
		this.versionNo = versionNo;
		this.delFlag = delFlag;
		this.registerDatetime = registerDatetime;
		this.registerUser = registerUser;
		this.registerProcess = registerProcess;
		this.updateDatetime = updateDatetime;
		this.updateUser = updateUser;
		this.updateProcess = updateProcess;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "table_name", nullable = false, length = 40)
	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	@Column(name = "key_1", nullable = false, length = 40)
	public String getKey1() {
		return this.key1;
	}

	public void setKey1(String key1) {
		this.key1 = key1;
	}

	@Column(name = "key_2", nullable = false, length = 100)
	public String getKey2() {
		return this.key2;
	}

	public void setKey2(String key2) {
		this.key2 = key2;
	}

	@Column(name = "s1_data", length = 65535)
	@Type(type="text")
	public String getS1Data() {
		return this.s1Data;
	}

	public void setS1Data(String s1Data) {
		this.s1Data = s1Data;
	}

	@Column(name = "s2_data", length = 100)
	public String getS2Data() {
		return this.s2Data;
	}

	public void setS2Data(String s2Data) {
		this.s2Data = s2Data;
	}

	@Column(name = "s3_data", length = 100)
	public String getS3Data() {
		return this.s3Data;
	}

	public void setS3Data(String s3Data) {
		this.s3Data = s3Data;
	}

	@Column(name = "n1_data", precision = 20)
	public BigDecimal getN1Data() {
		return this.n1Data;
	}

	public void setN1Data(BigDecimal n1Data) {
		this.n1Data = n1Data;
	}

	@Column(name = "n2_data", precision = 20)
	public BigDecimal getN2Data() {
		return this.n2Data;
	}

	public void setN2Data(BigDecimal n2Data) {
		this.n2Data = n2Data;
	}

	@Column(name = "n3_data", precision = 20)
	public BigDecimal getN3Data() {
		return this.n3Data;
	}

	public void setN3Data(BigDecimal n3Data) {
		this.n3Data = n3Data;
	}

	@Column(name = "version_no", nullable = false)
	public int getVersionNo() {
		return this.versionNo;
	}

	public void setVersionNo(int versionNo) {
		this.versionNo = versionNo;
	}

	@Column(name = "del_flag", nullable = false)
	public int getDelFlag() {
		return this.delFlag;
	}

	public void setDelFlag(int delFlag) {
		this.delFlag = delFlag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "register_datetime", nullable = false, length = 19)
	public Date getRegisterDatetime() {
		return this.registerDatetime;
	}

	public void setRegisterDatetime(Date registerDatetime) {
		this.registerDatetime = registerDatetime;
	}

	@Column(name = "register_user", nullable = false, length = 30)
	public String getRegisterUser() {
		return this.registerUser;
	}

	public void setRegisterUser(String registerUser) {
		this.registerUser = registerUser;
	}

	@Column(name = "register_process", nullable = false, length = 30)
	public String getRegisterProcess() {
		return this.registerProcess;
	}

	public void setRegisterProcess(String registerProcess) {
		this.registerProcess = registerProcess;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_datetime", nullable = false, length = 19)
	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

	@Column(name = "update_user", nullable = false, length = 30)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@Column(name = "update_process", nullable = false, length = 30)
	public String getUpdateProcess() {
		return this.updateProcess;
	}

	public void setUpdateProcess(String updateProcess) {
		this.updateProcess = updateProcess;
	}

}
